import { MedusaService } from "@medusajs/framework/utils"
import CreatorProfile from "./models/creator-profile"

/**
 * CreatorProfileModuleService.
 *
 * CRUD for creator metadata is auto-generated by the `MedusaService` factory
 * (createCreatorProfiles, listCreatorProfiles, ...). Add Stripe Connect
 * onboarding helpers here as the creator payout flow is built out.
 */
class CreatorProfileModuleService extends MedusaService({ CreatorProfile }) {
  async getBySlug(slug: string) {
    const [profile] = await this.listCreatorProfiles({ slug }, { take: 1 })
    return profile
  }
}

export default CreatorProfileModuleService
